version: 2

sources:
  - name: bronze
    database: "{{ 'brewline-coffee-co' if target.type == 'bigquery' else target.database }}"
    schema: bronze
    tables:
      - name: shopify_orders
      - name: square_transactions
      - name: recharge_subscriptions
      - name: zendesk_tickets
      - name: shipstation_shipments