FROM python:3.12-slim AS base
WORKDIR /opt/project
COPY pyproject.toml ./
COPY brewline/ ./brewline/
RUN pip install --no-cache-dir -e .

FROM base AS local

FROM base AS gcp
RUN pip install --no-cache-dir -e ".[gcp]"