# airflow/Dockerfile
FROM apache/airflow:2.10.5
RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.12.txt" \
    apache-airflow-providers-docker