FROM python:3.12-slim AS base
WORKDIR /opt/project
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM base AS local
# local dev only needs the base layer

FROM base AS gcp
COPY requirements-gcp.txt .
RUN pip install --no-cache-dir -r requirements-gcp.txt