brewline_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '../brewline.duckdb') }}"
    bigquery:
      type: bigquery
      method: oauth
      impersonate_service_account: brewline-dbt-transform@brewline-coffee-co.iam.gserviceaccount.com
      project: brewline-coffee-co
      dataset: silver
      threads: 4